import './js/api';
import './js/header';
import './js/tech-skills';
import './js/my-projects';
import './js/faq';
import './js/reviews';
import './js/work-together';
import './js/sidebar';
import './js/surprise';
